name: Test and Build Python package

on:
  push:
    branches:
      - test
  pull_request:
    types: [closed]
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install tox
    - name: Run tests - py38
      run: |
        tox -e testenv
        tox -e black
        tox -e mypy
        tox -e build-check
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install tox
    - name: Run tests - py39
      run: |
        tox -e testenv
        tox -e black
        tox -e mypy
        tox -e build-check
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install tox
    - name: Run tests - py310
      run: |
        tox -e testenv
        tox -e black
        tox -e mypy
        tox -e build-check

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' && (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'master')

    steps:
    - name: Build Module
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Build and upload to test.pypi
      env:
        TEST_TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TEST_TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        run: |
        pip install --upgrade pip
        pip install --upgrade build twine
        python -m build
        twine upload --u $TEST_TWINE_USERNAME --p $TEST_TWINE_PASSWORD --skip-existing --repository-url https://test.pypi.org/legacy/  dist/*
        echo "Package deployed to Test PyPI"
    - name: Build and upload to PyPI
      if: startsWith(github.ref, 'refs/tags/release-')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        run: |
        pip install --upgrade pip
        pip install --upgrade build twine
        python -m build
        ls -l dist
        twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD --skip-existing --repository-url https://upload.pypi.org/legacy/ dist/*
