name: Test and Build Python package

on:
  push:
    branches:
      - test
      - develop
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install tox
    - name: Run tests - py38
      run: |
        tox -e testenv
        tox -e black
        tox -e mypy
        tox -e build-check
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install tox
    - name: Run tests - py39
      run: |
        tox -e testenv
        tox -e black
        tox -e mypy
        tox -e build-check
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install tox
    - name: Run tests - py310
      run: |
        tox -e testenv
        tox -e black
        tox -e mypy
        tox -e build-check

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' && (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'master')

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: |
        python -m build --outdir dist/
    - name: Build and upload to test.pypi
      env:
        TEST_TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TEST_TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${TEST_TWINE_PASSWORD}
        repository_url: https://test.pypi.org/legacy/
    - name: Build and upload to PyPI
      if: startsWith(github.ref, 'refs/tags')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${TWINE_PASSWORD}
        
